# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java-version: [ 8, 11, 17 ]
        os: [ "ubuntu-latest" ]

    # https://docs.github.com/zh/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservices
    services:
      mysql:
        image: mysql:8.0.32
        ports:
          - 3306:3306
        env:
          # 创建 MySQL 环境变量：
          # https://hub.docker.com/_/mysql/
          # 数据库名
          MYSQL_DATABASE: coverage_jacoco
          # 数据库密码
          MYSQL_ROOT_PASSWORD: xuxiaowei.com.cn

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: RUN ENV
        id: run
        # bash, sh, cmd, powershell, pwsh
        # shell 类型必须为 sh，否则：
        # $GITHUB_ENV：仅支持 ubuntu、macos
        # $env:GITHUB_ENV：仅支持 windows
        shell: sh
        run: |
          echo "MYSQL_ROOT_PASSWORD=xuxiaowei.com.cn" >> $GITHUB_ENV
          echo "COVERAGE_JACOCO_MYSQL_HOST=localhost" >> $GITHUB_ENV
          echo "COVERAGE_JACOCO_MYSQL_DATABASE=coverage_jacoco" >> $GITHUB_ENV

      - name: Wait for MySQL
        run: |
          until docker exec $(docker ps -qf "ancestor=mysql:8.0.32") mysqladmin ping --silent; do
              echo 'Waiting for MySQL to be available...'
              sleep 1
          done

      # 初始化 MySQL
      - name: Init MySQL
        run: |
          # MySQL 版本
          mysql --version
          # 创建表结构
          mysql -u root -p ${{ env.MYSQL_ROOT_PASSWORD }} --host=${{ env.COVERAGE_JACOCO_MYSQL_HOST }} ${{ env.COVERAGE_JACOCO_MYSQL_DATABASE }} < docs/sql/1-table.sql
          # 插入数据
          mysql -u root -p ${{ env.MYSQL_ROOT_PASSWORD }} --host=${{ env.COVERAGE_JACOCO_MYSQL_HOST }} ${{ env.COVERAGE_JACOCO_MYSQL_DATABASE }} < docs/sql/2-data.sql

      # 设置JDK版本
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Cache modules
        uses: actions/cache@v3
        id: cache-modules
        with:
          path: |
            ~/.m2/repository
            ~/.npm
            $GITHUB_WORKSPACE/passport-ui/node/
            $GITHUB_WORKSPACE/passport-ui/node_modules/
            $GITHUB_WORKSPACE/ui/node/
            $GITHUB_WORKSPACE/ui/node_modules/
          key: ${{ matrix.os }}-${{ hashFiles('pom.xml', '**/pom.xml', '**/**/pom.xml', '**/package.json') }}
          restore-keys: |
            ${{ matrix.os }}-

      - name: CI ENV
        id: date
        # bash, sh, cmd, powershell, pwsh
        # shell 类型必须为 sh，否则：
        # $GITHUB_ENV：仅支持 ubuntu、macos
        # $env:GITHUB_ENV：仅支持 windows
        shell: sh
        run: |
          env
          echo $GITHUB_RUN_ID
          echo $GITHUB_JOB-${{ matrix.java-version }}
          echo "CI_PIPELINE_ID=$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "CI_JOB_ID=$GITHUB_JOB-${{ matrix.java-version }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: |
          mvn clean -e -U package source:jar javadoc:jar install -DskipTests

      # https://app.codecov.io/gh/xuxiaowei-com-cn/coverage-jacoco/new
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
